### ISSUE TITLE
ASSIGNMENT 1A

### ISSUE THREAD

**Issue by azmanyasin** [SKIP1013-A211-GROUP-A/WEEK-4#1]
### **INSTRUCTION**
Say your brother wants to buy a used car for $5,000 and has only $2,000 for the down payment. 
He hits you up for a loan for the remaining $3,000. 
If the length of the loan is five years and he’s paying you simple interest of 3.5 percent per year to borrow the additional $3,000, 
Calculate the sum of interest, monthly payment, and a total of payment.

### Output:
Enter the yearly interest rate, for example, 3.5: 3.5
Enter the number of years as an integer, for example, 5: 5
Enter the loan amount, for example, 3000.00: 3000
The monthly payment is $105.0
The total payment is $6300.0

### **SUBMISSION**
1. Complete code and Comment for each line of code
2. Sample Output
3. Due date: 2.15 PM (**TODAY**-8 November 2021)

**Comment by MohamadHafizal** [comment]
https://github.com/SKIP1013-Hafizal/WEEK-4.git

**Comment by AsyraafDanial-284368** [comment]
https://github.com/SKIP1013-ASYRAAF-DANIAL/WEEK-4.git

**Comment by nurezurinfarisha** [comment]
https://github.com/SKIP1013-Nur-Ezurin/WEEK-4.git

**Comment by KaaminiKulanthlu** [comment]
https://github.com/SKIP1013-Kaamini/ASSIGNMENT.git

**Comment by NurShazlinIwani** [comment]
https://github.com/SKIP1013-Nur-Shazlin-Iwani/WEEK4.git

**Comment by enfernal777** [comment]
https://github.com/SKIP1013-MUHAMMAD-ABQARI-BIN-ZULKIFLI/WEEK-4.git

**Comment by SuchiraSumon** [comment]
https://github.com/SKIP1013-SUCHIRA/WEEK-4.git

**Comment by FawatimNuralAin** [comment]
https://github.com/SKIP1013-Fawatim/WEEK4.git

**Comment by Anuarul-Irfan** [comment]
https://github.com/Anuarul-Irfan/WEEK-4.git

**Comment by CHONGPAOLUN284508** [comment]
https://github.com/SKIP1013-Chong-Pao-Lun/WEEK4.git

**Comment by HarshiniAlages288286** [comment]
https://github.com/SKIP1013-HARSHINI-ALAGES-288286/WEEK4.git

**Comment by NurulAzurin** [comment]
https://github.com/SKIP1013-NURUL-AZURIN/WEEK-4.git

**Comment by William284613** [comment]
https://github.com/SKIP-1013-William-Ng-Wei-Yi/Week-4.git

**Comment by NurinAndriana** [comment]
https://github.com/SKIP1013-Nurin-Andriana/WEEK-4.git

**Comment by TanZhiXian284333** [comment]
https://github.com/SKIP1013-TAN-ZHI-XIAN/WEEK-4-ASSIGNMENT.git

**Comment by NorshazlynIdayu** [comment]
https://github.com/SKIP1013-Norshazlyn/WEEK-4.git

**Comment by MariamMaisarah284251** [comment]
https://github.com/SKIP1013-Mariam-Maisarah/WEEK-4.git

**Comment by ImanZulhakim** [comment]
https://github.com/SKIP1013-ImanZulhakim/WEEK-4.git

**Comment by Anuarul-Irfan** [comment]
https://github.com/SKIP1013-ANUARUL-IRFAN/WEEK-4.git

**Comment by NoorAisyahHanumBintiMohdHisyam** [comment]
https://github.com/SKIP1013-NOOR-AISYAH-HANUM/WEEK4.git

**Comment by AinurHanim** [comment]
https://github.com/AinurHanim/WEEK-4.git

**Comment by Thivya700** [comment]
https://github.com/SKIP1013-THIVYA-SRI/WEEK4.git

**Comment by azibfikri** [comment]
https://github.com/SKIP1013-AZIB-FIKRI/WEEK4.git

**Comment by AhmadZuhairi17** [comment]
https://github.com/AhmadZuhairi17/WEEK-4.git

**Comment by NUR-SUHAILA-YEOP** [comment]
https://github.com/SKIP1013-NUR-SUHAILA/WEEK-4.git

**Comment by 0x251e** [comment]
https://github.com/SKIP1013-Shreethaar/WEEK-4.git

**Comment by DayangZakii** [comment]
https://github.com/SKIP1013-DAYANG-FATIMAH/WEEK-4.git

**Comment by naddyella** [comment]
https://github.com/SKIP1013-Nur-Adila/WEEK4.git

**Comment by TahfizHanapi** [comment]
https://github.com/TahfizHanapi/WEEK-5.git

**Comment by luqmanzamri** [comment]
https://github.com/luqmanzamri/week4.git

**Comment by fasihatul** [comment]
https://github.com/SKIP1013-FASIHATUL/WEEK-4.git

**Comment by NurulShakirah** [comment]
https://github.com/SKIP1013-A-NurulShakirah/WEEK-4.git

**Comment by nurinizzah** [comment]
https://github.com/SKIP1013-Nurin-Izzah/WEEK-4.git
