### ISSUE TITLE
ASSIGNMENT 1B

### ISSUE THREAD

**Issue by azmanyasin** [SKIP1013-A211-GROUP-A/WEEK-4#2]
### **INSTRUCTION**
You are required to calculate the total price that needs to be paid by a customer in C_MARTS shopping complex. The program should ask how many items that the customer buys (the maximum number of items is 3). Based on the number of items, the program will ask the quantity and price of each item. Each time the quantity and price are entered, they must be multiplied and totaled up. Then, the program should calculate the discount obtained by the customer based on the total price. If the customer buys more than RM100, he/she is entitled to a 20% discount, whereas, if the total price is less than RM100 the customer is only entitled to 10% discount. Finally, the program should display the total price before discount, discount received and the amount that needs to be paid. 

**Example of sample running (underlined are the input):**
![image](https://user-images.githubusercontent.com/61673158/140629005-6af36f07-d719-44c0-97b5-82dd08088fde.png)

### **SUBMISSION**
1. Complete Code and Comment for each line of code
2. Sample Output
3. Due Date: 2.15 PM (**TODAY** - 8 November 2021)

**Comment by NoorAisyahHanumBintiMohdHisyam** [comment]
https://github.com/SKIP1013-NOOR-AISYAH-HANUM/WEEK4.git

**Comment by NurShazlinIwani** [comment]
https://github.com/SKIP1013-Nur-Shazlin-Iwani/WEEK4.git

**Comment by nurezurinfarisha** [comment]
https://github.com/SKIP1013-Nur-Ezurin/WEEK-4.git

**Comment by SuchiraSumon** [comment]
https://github.com/SKIP1013-SUCHIRA/WEEK-4.git

**Comment by HarshiniAlages288286** [comment]
https://github.com/SKIP1013-HARSHINI-ALAGES-288286/WEEK4.git

**Comment by CHONGPAOLUN284508** [comment]
https://github.com/SKIP1013-Chong-Pao-Lun/WEEK4.git

**Comment by NurulAzurin** [comment]
https://github.com/SKIP1013-NURUL-AZURIN/WEEK-4.git

**Comment by William284613** [comment]
https://github.com/SKIP-1013-William-Ng-Wei-Yi/Week-4.git

**Comment by AsyraafDanial-284368** [comment]
https://github.com/SKIP1013-ASYRAAF-DANIAL/WEEK-4.git

**Comment by TanZhiXian284333** [comment]
https://github.com/SKIP1013-TAN-ZHI-XIAN/WEEK-4-ASSIGNMENT.git

**Comment by NorshazlynIdayu** [comment]
https://github.com/SKIP1013-Norshazlyn/WEEK-4.git

**Comment by ImanZulhakim** [comment]
https://github.com/SKIP1013-ImanZulhakim/WEEK-4.git

**Comment by MariamMaisarah284251** [comment]
https://github.com/SKIP1013-Mariam-Maisarah/WEEK-4.git

**Comment by Anuarul-Irfan** [comment]
https://github.com/Anuarul-Irfan/WEEK-4.git

**Comment by MohamadHafizal** [comment]
https://github.com/SKIP1013-Hafizal/WEEK-4.git

**Comment by NurinAndriana** [comment]
https://github.com/SKIP1013-Nurin-Andriana/WEEK-4.git

**Comment by Anuarul-Irfan** [comment]
https://github.com/SKIP1013-ANUARUL-IRFAN/WEEK-4.git

**Comment by Thivya700** [comment]
https://github.com/SKIP1013-THIVYA-SRI/WEEK4.git

**Comment by azibfikri** [comment]
https://github.com/SKIP1013-AZIB-FIKRI/WEEK4.git

**Comment by AhmadZuhairi17** [comment]
https://github.com/AhmadZuhairi17/WEEK-4.git

**Comment by FawatimNuralAin** [comment]
https://github.com/SKIP1013-Fawatim/WEEK4.git

**Comment by naddyella** [comment]
https://github.com/SKIP1013-Nur-Adila/WEEK4.git

**Comment by KaaminiKulanthlu** [comment]
https://github.com/SKIP1013-Kaamini/ASSIGNMENT.git

**Comment by TahfizHanapi** [comment]
https://github.com/TahfizHanapi/WEEK-5.git

**Comment by DayangZakii** [comment]
https://github.com/SKIP1013-DAYANG-FATIMAH/WEEK-4.git

**Comment by fasihatul** [comment]
https://github.com/SKIP1013-FASIHATUL/WEEK-4.git

**Comment by nurinizzah** [comment]
https://github.com/SKIP1013-Nurin-Izzah/WEEK-4.git

**Comment by enfernal777** [comment]
https://github.com/SKIP1013-MUHAMMAD-ABQARI-BIN-ZULKIFLI/WEEK-4.git

**Comment by AinurHanim** [comment]
https://github.com/AinurHanim/WEEK-4.git
